# Generated by Django 2.0 on 2017-12-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilet_tur', models.CharField(max_length=60)),
                ('bilet_fiyat', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Filmler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_afis', models.ImageField(upload_to='')),
                ('film_adi', models.CharField(max_length=100)),
                ('film_yil', models.DateField()),
                ('film_aktor', models.CharField(max_length=120)),
                ('film_aktris', models.CharField(max_length=120)),
                ('film_yonetmen', models.CharField(max_length=120)),
                ('film_dil', models.CharField(max_length=120)),
                ('film_sure', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salonlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_adi', models.CharField(max_length=60)),
                ('salon_kapasite', models.IntegerField()),
                ('ses_sistemi', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Seanslar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seans_zaman', models.CharField(choices=[('Sabah', 'Sabah'), ('Ogle', 'Ogle'), ('Aksam', 'Aksam')], max_length=100)),
                ('film_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinema.Filmler')),
                ('salon_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinema.Salonlar')),
            ],
        ),
        migrations.CreateModel(
            name='Sinemalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinema_adi', models.CharField(max_length=120)),
                ('sinema_yeri', models.CharField(max_length=120)),
                ('salon_sayisi', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='salonlar',
            name='sinema_adi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinema.Sinemalar'),
        ),
    ]
